name: Docker build and deploy

on:
  push:
    branches: [ develop, master ]
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and deploy image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GithubActionsSession
        aws-region: us-east-2
      if: github.event_name != 'pull_request'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      if: github.event_name != 'pull_request'

    - name: Prepare values
      id: prepare
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: escrow-dashboard
      run: |
        IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA::7}-$(date +%s)
        TAGGED_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
        echo "tagged_image=${TAGGED_IMAGE}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the image
      id: build-image
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push the image to Amazon ECR
      id: build-push-image
      if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.tagged_image }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Manual approval for deploy to Prod
      id: manual-approval-prod
      if: github.ref == 'refs/heads/master'
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GH_TOKEN }}
        approvers: vkomodey,AmrEssamSh,ivhus,posix4e
        minimum-approvals: 1

    - name: Get Github action IP
      id: ip
      if: github.event_name != 'pull_request'
      uses: haythem/public-ip@v1.2

    - name: Configure SSH
      id: configure-ssh
      if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
      run: |
        mkdir -p ~/.ssh/
        aws ssm get-parameter --region us-east-2 --name 'SSH_KEY_FOR_CD' --with-decryption --query 'Parameter.Value' --output text > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName ${{ secrets.STAGING_VM_IP }}
          User ec2-user
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        Host prod
          HostName ${{ secrets.PROD_VM_IP }}
          User ec2-user
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END

    - name: Add Github Actions IP to Security group
      id: add-ip-to-sg
      if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
      run: |
        aws ec2 authorize-security-group-ingress --group-id sg-009e380719581702e --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Copy launcher to Staging server
      id: launcher-to-staging
      if: github.ref == 'refs/heads/develop'
      run: |
        scp .github/workflows/common/deploy.bash staging:~/deploy.bash

    - name: Copy launcher to Prod server
      id: launcher-to-prod
      if: github.ref == 'refs/heads/master'
      run: |
        scp .github/workflows/common/deploy.bash prod:~/deploy.bash

    - name: Run on Staging server
      id: run-on-staging
      if: github.ref == 'refs/heads/develop'
      run: |
        ssh staging '/usr/bin/env bash ~/deploy.bash ${{ env.tagged_image }}'

    - name: Run on Prod server
      id: run-on-prod
      if: github.ref == 'refs/heads/master'
      run: |
        ssh prod '/usr/bin/env bash ~/deploy.bash ${{ env.tagged_image }}'

    - name: Remove Github Actions IP from security group
      id: remove-ip-from-sg
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && always()
      run: |
        aws ec2 revoke-security-group-ingress --group-id sg-009e380719581702e --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
